### ISSUE TITLE
Document How to Change Asset Directory

### ISSUE THREAD

**Issue by zoffixznet** [jhthorsen/mojolicious-plugin-assetpack#101]
The default `$home/assets` directory is not watched by morbo by default. This makes it a rather poor choice to store assets in, so I'd like to change its location, however, browsing the main docs and the tutorial, I'm yet to find how to accomplish that.

It would be nice to have an example documented maybe [here](https://metacpan.org/pod/distribution/Mojolicious-Plugin-AssetPack/lib/Mojolicious/Plugin/AssetPack/Guides/Tutorial.pod#On-disk). That section does mention `::Store` but I don't understand what relevance it has to where the assets are looked at or how to get to an instance of the appropriate `::Store`

**Comment by jhthorsen** [comment]
I don't mind code examples that makes it easier to understand 👍 

However, it was my intention that this should explain it: "Mojolicious::Plugin::AssetPack::Store is a sub class of Mojolicious::Static, allowing it to find files relative to "paths" in Mojolicious::Static."

Here is where you can change where assetpack looks for files:

    $app->asset->store->paths(["/some/new/location", "/other/location"]);

Here is where you change where assetpack write files:

    $app->asset->store->paths->[0] = "/some/location";

I think maybe this should be documented inside https://metacpan.org/pod/Mojolicious::Plugin::AssetPack::Store. I do think that maybe more of the methods/attributes from Mojolicious::Static should be documented in a SYNOPSIS section.

I very much appreciate if you give this a spin. I don't mind helping out, but since I've already failed, it might be a good idea if someone else looked at it.

**Comment by jhthorsen** [comment]
Do you want me to work on a SYNOPSIS for M::P::A::Store?

**Comment by zoffixznet** [comment]
> Do you want me to work on a SYNOPSIS for M::P::A::Store?

¯\_(ツ)_/¯ The code example I added in the tutorial would be enough for me to figure out how to get set up the custom paths. I now realize there's a `->store` method in M::P::A, but it didn't occur to me to look for something like that when I read in the Tutorial about ::Store.

**Comment by jhthorsen** [comment]
What do you think about a7e0ec8?

**Comment by zoffixznet** [comment]
:+1:

**Comment by jhthorsen** [comment]
Cool! Thanks 👍
