### ISSUE TITLE
Enhancement req: loud comment minifying

### ISSUE THREAD

**Issue by rpcme** [jhthorsen/mojolicious-plugin-assetpack#17]
Not sure if this is entirely possible if the developer does not use annotations but minifying /*! */ strings would be good.

**Comment by jhthorsen** [comment]
@rpcme: I'm closing this now, since I don't think I want to fix this in AssetPack.

One possible solution (I think) is to use https://metacpan.org/pod/Mojolicious::Plugin::Browserify instead, which require browserify to work.

Please re-open if you have any ideas on how to make this work in AssetPack @rpcme.

Thanks for the issue! :smiley:

**Comment by rpcme** [comment]
No problem ;)
