### ISSUE TITLE
Documentation mentions removed "expand" method

### ISSUE THREAD

**Issue by jberger** [jhthorsen/mojolicious-plugin-assetpack#38]
The development section appears to need updating, see here:

https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack.pm#L82-L95

**Comment by jhthorsen** [comment]
Fixed in 0.3801.

Please review the new documentation:
* https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Manual/Assets.pod
* https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Manual/Include.pod
* https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Manual/Modes.pod
* https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Manual/CustomDomain.pod

**Comment by jhthorsen** [comment]
Seems like this is fixed.
