### ISSUE TITLE
Cache-Control on assets

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/mojolicious-plugin-assetpack#55]
There's no obvious way to set the Cache-Control headers for packed asset files, and they don't appear to get set by default.

Unless I'm mistaken, then a suitably random filename is created for on disk packed assets and thus we should be safe to set a super long cache-control header on said files to prevent the browser from attempting to load them too often.

**Comment by jhthorsen** [comment]
It depends, since AssetPack can create two types of Assets:

* in-memory: These assets are served by a "before_routes" hook inside AssetPack, so we can easily change the ```Cache-Control``` header. https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack.pm#L121 
* on disk assets: This one is a bit tougher: These assets are served by Mojolicious, meaing the AssetPack code is not involved at all. https://github.com/kraih/mojo/blob/master/lib/Mojolicious.pm#L96

We could add a "after_static" hook in AssetPack which sets the Cache-Control header if it's serving a file from ```/packed/```. Something like this:

```
$app->hook(after_static => sub {
  my $c = shift;
  my $path = $c->req->url->path;
  return unless $path->[1] and 0 == index "$path", $self->base_url;

  # this line can also be added to the in-memory hook:
  $c->res->headers->cache_control("max-age=31556926");
});
```

**Comment by jhthorsen** [comment]
I need someone to implement and write some tests for this, and I also need a +1 from some other person before I actually merge it, since I'm not sure if this is really required and if it could add some unknown issues. I guess there could be an option to add the hook, like:
```
plugin AssetPack => {max_age => 31556926};
```

Also, If you haven't created a PR before, then check out: #53 and https://help.github.com/articles/creating-a-pull-request/

**Comment by marcusramberg** [comment]
:+1: from me on this, it seems like a very logical addition, and something I would expect an asset pipeline to do.

**Comment by jhthorsen** [comment]
I'm also unsure about the implementation I suggested. Need feedback and tests and documentation. Preferably a pull request :)

**Comment by mrenvoize** [comment]
Cheers guys, 

I'll have a bit of a bash around with this.. see if I can come up with something worthy of a PR.

**Comment by zoffixznet** [comment]
+1 from me too

**Comment by mrenvoize** [comment]
Interestingly enough we're starting to throw ideas around about this again at work this week.  I can't see myself getting much time to work on it for another month or so unfortunately. Need to get the beta of the door first.

**Comment by jhthorsen** [comment]
I haven't gotten any feedback on the suggested solution: Is an "after_static" hook the right thing to do?

**Comment by zoffixznet** [comment]
> I haven't gotten any feedback on the suggested solution: Is an "after_static" hook the right thing to do?

Sounds like the way to go to me.

**Comment by jhthorsen** [comment]
OK! Please review 84776c4 and let me know what you think.

**Comment by zoffixznet** [comment]
:+1: looks good to me.

**Comment by jhthorsen** [comment]
Ok :smile: 

0.63 is soon available on CPAN. Feedback is very much appreciated.
