### ISSUE TITLE
Make AssetPack modules optional in production

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/mojolicious-plugin-assetpack#59]
Would be very cool if the people who run the application didn't require the same amount of dependencies as the developers. In the code below, only the AssetPack plugin is really required for production. (Or maybe not even AssetPack..?) Riotjs, FontAwesome4 and Bootstrap3 only contains the input files required to make the packed files.

```
  $self->plugin('AssetPack', {source_paths => ['assets'], proxy => 'detect'});
  $self->plugin('Riotjs');
  $self->plugin('FontAwesome4', {css => []});
  $ENV{SASS_PATH} = Mojolicious::Plugin::FontAwesome4->asset_path('sass');
  $self->plugin('Bootstrap3');
```

Maybe it could be possible to make AssetPack load the other plugins, but only if the packed file doesn't already exists?

**Comment by jhthorsen** [comment]
When I say "not even AssetPack", I'm thinking that maybe AssetPack could make a "shim" for itself that only load the rest of the code when needed.

**Comment by zoffixznet** [comment]
> Would be very cool if the people who run the application didn't require the same amount of dependencies as the developers.

Not sure. If the production has gone as far as install Mojolicious and other deps or simply have all the deps pre-packaged with the app... what worth is a few extra automatically-installed modules to them?

> maybe AssetPack could make a "shim" for itself

I don't think I fully understand how that would work from the point of view of a developer. You add the shim, but then...? Do you have to re-generate the shim every time you alter what assets you include in your app? Do you have to remove all the `->plugin('Bootstrap3')` type of stuff from your app and replace it with a shim? And when you'd like to add another AssetPack-using plugin to your app, do you have to restore the removed `->plugin(...` stuff just so you could re-generate the shim?

I don't think I'd ever bother doing this stuff, since my apps would just auto-install the deps from CPAN. And those that don't install from CPAN likely just package the deps with their app. Even if I had to generate the shim and add its code into my app just a single time, I think I'd consider it a wasted effort made for the sake of excluding a couple of modules from the deps

My two cents :)

**Comment by jhthorsen** [comment]
The issue arise when you require the consumer of the application to install "sass", "less", "riot" or some other third party processor.

The shim would not take into account the complicated situation where the user do a lot of manipulation on the $app->asset object, but in the first edition only make sure that the assets are available. In this simple case, the shim would read a "mapping.json" file in public/packed which describe which processed file "asset.css" points to in which environment.

The usecase when this is important is when we fix issues such as #60, which change the checksum of the processed file. In the stable case, we simply check the input files, get the same checksum and no third party applications are required.

About the plugin loading: Plugins such as "Bootstrap3" could be loaded through the shim:

    $app->asset->plugin("Bootstrap3");

The custom "plugin" method in the shim would not load Bootstrap3, unless it is available.

(Hope I have answered all the questions)

**Comment by jhthorsen** [comment]
Maybe the commit above has a better explanation to what I try to achieve.

**Comment by zoffixznet** [comment]
Ah, right. I totally forgot about needing sass and other things. Then yes, this would be useful and the way you describe how it would work makes sense now.

**Comment by jhthorsen** [comment]
So do you think it's worth continuing on d56b71a?
Do you think it would be even more useful to have a "shim", so you don't even need assetpack?

Not sure in what direction to take this now.

**Comment by zoffixznet** [comment]
> So do you think it's worth continuing on d56b71a?
> Does the documentation for d56b71a make sense? (never mind all the typos, haha)
Yeah, looks decent to me and documentation does make sense.

> Do you think it would be even more useful to have a "shim", so you don't even need assetpack?
Don't know. Would that avoid requiring something that isn't readily available from CPAN and can be packaged with the app? I see some `::XS` modules as prereqs to `AssetPack`. Would having a shim allow for installing a hypothetical Mojolicious app on a box that doesn't have a C compiler? I think I'm entirely neutral on the idea of a shim: neither love it nor hate it :smile_cat: 


Not sure in what direction to take this now.

**Comment by jhthorsen** [comment]
Cool. Thanks for the input.

Yes, a "shim" would not require AssetPack, and therefor none of the dependencies.

**Comment by jhthorsen** [comment]
I'm closing this issue with 113809d. I think it does the same thing, just that you need to add the loading of optional modules inside an eval. Maybe not pretty, but it makes it even more explicit IMO.
