### ISSUE TITLE
Can't detect extension from content type of header

### ISSUE THREAD

**Issue by keedi** [jhthorsen/mojolicious-plugin-assetpack#73]
Since `Mojolicious::Plugin::AssetPack::Handler::Http::asset_for()` uses `Mojolicious::Types::detect()` method, it can't detect proper extension from content type of the header. I think `detect()` method is used for `Accept` header so it is not exactly fit to detect extension. If content type is `text/css` then there is no problem. But if content type is `text/css; charset=utf-8` then `detect()` method failed to recognize. `detect()` uses following regex and code:

```
  # Extract and prioritize MIME types
  my %types;
  /^\s*([^,; ]+)(?:\s*\;\s*q\s*=\s*(\d+(?:\.\d+)?))?\s*$/i
    and $types{lc $1} = $2 // 1
    for split ',', $accept // '';
  my @detected = sort { $types{$b} <=> $types{$a} } sort keys %types;
```

In regex it uses `$` anchor, so regex will be failed to match, then the extension of `text/css; charset-utf8;` will be `txt` rather than `css`.

**Comment by jhthorsen** [comment]
I think this is fixed in the new version of AssetPack. Have a look at the resources below for more information:

* http://thorsen.pm/perl/2016/02/21/rewriting-assetpack-plugin.html
* https://github.com/jhthorsen/mojolicious-plugin-assetpack/tree/v2

The API is getting very stable now, even if I haven't gotten around to merge it. I would check it out.

**Comment by jhthorsen** [comment]
Please re-open with more information if this is still an issue in the 1.x versions.
