### ISSUE TITLE
Missing a way to export/dump the assets for packaging

### ISSUE THREAD

**Issue by coolo** [jhthorsen/mojolicious-plugin-assetpack#90]
Let me describe our use case: we have one app that we offer for download/installation ready made as a pakage. That package is both available from e.g. [Open Build Service](https://software.opensuse.org/download.html?project=devel%3AopenQA&package=openQA) as from Fedora's Rawhide.

Both share the same problem: we want as little external dependencies as possible - especially when deploying on production servers. So we pregenerate the assets to have them as static assets in the package and don't require the sass sources or even external network access from within the production system. Another problem are permissions: the environment running the app is highly boxed in a secured environment. And all this makes it very handy to _not_ require the app to create the assets, but have them ready in the package you can deploy anywhere.

So the package I'm preparing brings e.g. /usr/share/openqa/assets/cache/needlediff-d5af99e8a7.min.js but no sources to this asset. But asset->process still wants to find all the sources to it, which will not work in our environment.

```
Jun 01 11:28:32 tortuga openqa[23904]: Uncaught exception from user code:
Jun 01 11:28:32 tortuga openqa[23904]: Could not find asset 'javascripts/needleedit.js'. at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious/Plugin/AssetPack.pm line 46.
Jun 01 11:28:32 tortuga openqa[23904]: Mojolicious::Plugin::AssetPack::process('Mojolicious::Plugin::AssetPack=HASH(0x8c02db0)', 'step_edit.js', 'javascripts/needleedit.js', 'javascripts/needleeditor.js', 'javascripts/shapes.js', 'javascripts/keyevent.js/') called at /usr/share/openqa/script/../lib/OpenQA/WebAPI.pm line 253
Jun 01 11:28:32 tortuga openqa[23904]: OpenQA::WebAPI::startup('OpenQA::WebAPI=HASH(0x23b0f70)') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious.pm line 168
Jun 01 11:28:32 tortuga openqa[23904]: Mojolicious::new('OpenQA::WebAPI') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojo/Server.pm line 17
Jun 01 11:28:32 tortuga openqa[23904]: Mojo::Server::build_app('Mojo::Server=HASH(0x22a6f38)', 'OpenQA::WebAPI') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious/Commands.pm line 72
Jun 01 11:28:32 tortuga openqa[23904]: Mojolicious::Commands::start_app('Mojolicious::Commands', 'OpenQA::WebAPI') called at /usr/share/openqa/script/../lib/OpenQA/WebAPI.pm line 593
Jun 01 11:28:32 tortuga openqa[23904]: OpenQA::WebAPI::run() called at /usr/share/openqa/script/openqa line 35
```

Issue #81 suggested an export pipe, which sounds promising - but it would still require process to ignore sources in production.

**Comment by coolo** [comment]
if I package the sources too, it works - which increases the package quite a bit

**Comment by jhthorsen** [comment]
What is the problem shipping with the sources?

I would like if there was possible to ship with a "assetpack shim", meaning a small chunk of code that would simply contain enough code for the helpers in the templates to work. This code could be generated from assetpack.db and not require any sources, pipes to be called at all.

This is just an idea, which I'm not going to pursue because I don't have the time to do it.

**Comment by jhthorsen** [comment]
I'm going to close this issue, since I don't think it will ever be supported.

You might also want to check out https://metacpan.org/pod/Mojolicious::Plugin::Webpack, since it indeed creates static files on the disk that is easy to package. The plugin also contains code that will automatically convert assetpack.def files into webpack entry files, so it shouldn't be too hard to try it out.
